// Central registry of all 100 websites
// 65 static + 35 dynamic

export const CATEGORIES = {
  STATIC: "Static",
  DYNAMIC: "Dynamic",
};

export const TAGS = {
  TOOL: "Tool",
  INFO: "Info",
  CREATIVE: "Creative",
  FUN: "Fun",
  PRODUCTIVITY: "Productivity",
  PORTFOLIO: "Portfolio",
  GAME: "Game",
  FINANCE: "Finance",
  HEALTH: "Health",
  EDUCATION: "Education",
  SOCIAL: "Social",
  TECH: "Tech",
  LIFESTYLE: "Lifestyle",
  UTILITY: "Utility",
};

export const sites = [
  // ─── STATIC SITES (1–65) ───────────────────────────────────────────────
  { id: 1,  slug: "color-palette-generator",  title: "Color Palette Generator",   description: "Generate beautiful color palettes instantly",   tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🎨", color: "#6366f1" },
  { id: 2,  slug: "css-gradient-maker",       title: "CSS Gradient Maker",         description: "Craft stunning CSS gradients with live preview", tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🌈", color: "#8b5cf6" },
  { id: 3,  slug: "unit-converter",           title: "Unit Converter",             description: "Convert between any units seamlessly",           tag: TAGS.UTILITY,     type: CATEGORIES.STATIC, icon: "⚖️", color: "#0ea5e9" },
  { id: 4,  slug: "countdown-timer",          title: "Countdown Timer",            description: "Sleek countdown timer for any occasion",         tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "⏳", color: "#f59e0b" },
  { id: 5,  slug: "pomodoro-clock",           title: "Pomodoro Clock",             description: "Stay focused with the Pomodoro technique",       tag: TAGS.PRODUCTIVITY,type: CATEGORIES.STATIC, icon: "🍅", color: "#ef4444" },
  { id: 6,  slug: "markdown-previewer",       title: "Markdown Previewer",         description: "Write and preview Markdown in real time",        tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "📝", color: "#10b981" },
  { id: 7,  slug: "password-generator",       title: "Password Generator",         description: "Generate strong, secure passwords instantly",    tag: TAGS.UTILITY,     type: CATEGORIES.STATIC, icon: "🔐", color: "#6366f1" },
  { id: 8,  slug: "bmi-calculator",           title: "BMI Calculator",             description: "Calculate your Body Mass Index easily",          tag: TAGS.HEALTH,      type: CATEGORIES.STATIC, icon: "💪", color: "#22c55e" },
  { id: 9,  slug: "tip-calculator",           title: "Tip Calculator",             description: "Split bills and calculate tips effortlessly",    tag: TAGS.FINANCE,     type: CATEGORIES.STATIC, icon: "💰", color: "#f59e0b" },
  { id: 10, slug: "age-calculator",           title: "Age Calculator",             description: "Find your exact age down to the second",         tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🎂", color: "#ec4899" },
  { id: 11, slug: "random-quote",             title: "Random Quote Generator",     description: "Get inspired with curated random quotes",        tag: TAGS.CREATIVE,    type: CATEGORIES.STATIC, icon: "💬", color: "#8b5cf6" },
  { id: 12, slug: "lorem-ipsum-generator",    title: "Lorem Ipsum Generator",      description: "Generate placeholder text on demand",            tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "📄", color: "#64748b" },
  { id: 13, slug: "character-counter",        title: "Character Counter",          description: "Count characters, words and sentences live",     tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🔢", color: "#0ea5e9" },
  { id: 14, slug: "base64-encoder",           title: "Base64 Encoder/Decoder",     description: "Encode and decode Base64 strings instantly",     tag: TAGS.TECH,        type: CATEGORIES.STATIC, icon: "🔀", color: "#6366f1" },
  { id: 15, slug: "json-formatter",           title: "JSON Formatter",             description: "Format and validate JSON with syntax highlight", tag: TAGS.TECH,        type: CATEGORIES.STATIC, icon: "{ }", color: "#10b981" },
  { id: 16, slug: "hex-rgb-converter",        title: "HEX ↔ RGB Converter",        description: "Convert between HEX and RGB color codes",        tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🎨", color: "#f43f5e" },
  { id: 17, slug: "stopwatch",                title: "Stopwatch",                  description: "Precision stopwatch with lap tracking",           tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "⏱️", color: "#0ea5e9" },
  { id: 18, slug: "qr-code-generator",        title: "QR Code Generator",          description: "Generate QR codes for any URL or text",          tag: TAGS.UTILITY,     type: CATEGORIES.STATIC, icon: "📱", color: "#1e293b" },
  { id: 19, slug: "text-case-converter",      title: "Text Case Converter",        description: "Convert text between UPPER, lower, Title etc",   tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "Aa", color: "#7c3aed" },
  { id: 20, slug: "number-to-words",          title: "Number to Words",            description: "Convert numbers into written English words",      tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🔤", color: "#059669" },
  { id: 21, slug: "roman-numeral-converter",  title: "Roman Numeral Converter",    description: "Convert between Arabic and Roman numerals",       tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "Ⅻ", color: "#d97706" },
  { id: 22, slug: "pixel-ruler",              title: "Pixel Ruler",                description: "On-screen ruler to measure elements in pixels",   tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "📏", color: "#475569" },
  { id: 23, slug: "aspect-ratio-calculator",  title: "Aspect Ratio Calculator",    description: "Calculate and maintain image aspect ratios",      tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🖼️", color: "#0284c7" },
  { id: 24, slug: "regex-tester",             title: "Regex Tester",               description: "Test regular expressions with live matching",     tag: TAGS.TECH,        type: CATEGORIES.STATIC, icon: "🔍", color: "#9333ea" },
  { id: 25, slug: "css-box-shadow-generator", title: "Box Shadow Generator",       description: "Visually create CSS box shadows",                 tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🪟", color: "#6366f1" },
  { id: 26, slug: "breathing-exercise",       title: "Breathing Exercise",         description: "Guided breathing exercises for calm and focus",   tag: TAGS.HEALTH,      type: CATEGORIES.STATIC, icon: "🧘", color: "#06b6d4" },
  { id: 27, slug: "digital-clock",            title: "Digital Clock",              description: "A beautiful real-time digital clock display",    tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🕐", color: "#1e40af" },
  { id: 28, slug: "world-clock",              title: "World Clock",                description: "View current time in major cities worldwide",     tag: TAGS.INFO,        type: CATEGORIES.STATIC, icon: "🌍", color: "#0369a1" },
  { id: 29, slug: "morse-code-translator",    title: "Morse Code Translator",      description: "Translate text to and from Morse code",           tag: TAGS.FUN,         type: CATEGORIES.STATIC, icon: "•−", color: "#78350f" },
  { id: 30, slug: "binary-converter",         title: "Binary Converter",           description: "Convert decimal, binary, hex and octal",         tag: TAGS.TECH,        type: CATEGORIES.STATIC, icon: "01", color: "#15803d" },
  { id: 31, slug: "todo-list",                title: "Todo List",                  description: "Clean, minimal to-do list with local storage",    tag: TAGS.PRODUCTIVITY,type: CATEGORIES.STATIC, icon: "✅", color: "#16a34a" },
  { id: 32, slug: "note-taking-app",          title: "Note Taking App",            description: "Sticky notes with persistence in your browser",   tag: TAGS.PRODUCTIVITY,type: CATEGORIES.STATIC, icon: "📌", color: "#ca8a04" },
  { id: 33, slug: "habit-tracker",            title: "Habit Tracker",              description: "Track daily habits and build streaks",            tag: TAGS.HEALTH,      type: CATEGORIES.STATIC, icon: "📈", color: "#059669" },
  { id: 34, slug: "flashcard-maker",          title: "Flashcard Maker",            description: "Create and study flashcards in your browser",     tag: TAGS.EDUCATION,   type: CATEGORIES.STATIC, icon: "🃏", color: "#7c3aed" },
  { id: 35, slug: "typing-speed-test",        title: "Typing Speed Test",          description: "Measure your WPM and accuracy while typing",      tag: TAGS.FUN,         type: CATEGORIES.STATIC, icon: "⌨️", color: "#0f172a" },
  { id: 36, slug: "snake-game",               title: "Snake Game",                 description: "Classic snake game in your browser",              tag: TAGS.GAME,        type: CATEGORIES.STATIC, icon: "🐍", color: "#166534" },
  { id: 37, slug: "tic-tac-toe",              title: "Tic Tac Toe",                description: "Play Tic Tac Toe against a friend or AI",         tag: TAGS.GAME,        type: CATEGORIES.STATIC, icon: "❌", color: "#1d4ed8" },
  { id: 38, slug: "memory-card-game",         title: "Memory Card Game",           description: "Flip cards and match pairs to win",               tag: TAGS.GAME,        type: CATEGORIES.STATIC, icon: "🧠", color: "#7e22ce" },
  { id: 39, slug: "rock-paper-scissors",      title: "Rock Paper Scissors",        description: "Challenge the computer to RPS",                   tag: TAGS.GAME,        type: CATEGORIES.STATIC, icon: "✊", color: "#b45309" },
  { id: 40, slug: "word-scramble",            title: "Word Scramble",              description: "Unscramble letters to find hidden words",         tag: TAGS.GAME,        type: CATEGORIES.STATIC, icon: "🔤", color: "#0891b2" },
  { id: 41, slug: "quiz-app",                 title: "Quiz App",                   description: "Test your general knowledge with random quizzes", tag: TAGS.EDUCATION,   type: CATEGORIES.STATIC, icon: "🧪", color: "#6d28d9" },
  { id: 42, slug: "calculator",               title: "Scientific Calculator",      description: "Full-featured scientific calculator",             tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🔢", color: "#374151" },
  { id: 43, slug: "loan-calculator",          title: "Loan Calculator",            description: "Calculate loan EMI, interest and schedule",       tag: TAGS.FINANCE,     type: CATEGORIES.STATIC, icon: "🏦", color: "#1e3a5f" },
  { id: 44, slug: "currency-converter-static",title: "Currency Converter",         description: "Convert between major world currencies",          tag: TAGS.FINANCE,     type: CATEGORIES.STATIC, icon: "💱", color: "#065f46" },
  { id: 45, slug: "calorie-counter",          title: "Calorie Counter",            description: "Track daily calorie intake and goals",            tag: TAGS.HEALTH,      type: CATEGORIES.STATIC, icon: "🥗", color: "#16a34a" },
  { id: 46, slug: "water-intake-tracker",     title: "Water Intake Tracker",       description: "Track your daily water intake goals",             tag: TAGS.HEALTH,      type: CATEGORIES.STATIC, icon: "💧", color: "#0ea5e9" },
  { id: 47, slug: "portfolio-template",       title: "Portfolio Template",         description: "A ready-to-use developer portfolio template",     tag: TAGS.PORTFOLIO,   type: CATEGORIES.STATIC, icon: "🧑‍💻", color: "#1e1b4b" },
  { id: 48, slug: "resume-builder",           title: "Resume Builder",             description: "Build a professional resume and export as PDF",   tag: TAGS.PRODUCTIVITY,type: CATEGORIES.STATIC, icon: "📋", color: "#1c1917" },
  { id: 49, slug: "invoice-generator",        title: "Invoice Generator",          description: "Generate professional invoices and print them",    tag: TAGS.FINANCE,     type: CATEGORIES.STATIC, icon: "🧾", color: "#1c1917" },
  { id: 50, slug: "color-blindness-checker",  title: "Color Blindness Checker",    description: "Simulate how colors look to color-blind users",   tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "👁️", color: "#7c3aed" },
  { id: 51, slug: "font-pairing-tool",        title: "Font Pairing Tool",          description: "Discover beautiful Google Fonts combinations",    tag: TAGS.CREATIVE,    type: CATEGORIES.STATIC, icon: "🔤", color: "#9333ea" },
  { id: 52, slug: "border-radius-preview",    title: "Border Radius Preview",      description: "Visually generate CSS border-radius values",      tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "⬛", color: "#475569" },
  { id: 53, slug: "svg-wave-generator",       title: "SVG Wave Generator",         description: "Create beautiful SVG wave dividers for websites",  tag: TAGS.CREATIVE,    type: CATEGORIES.STATIC, icon: "〰️", color: "#0284c7" },
  { id: 54, slug: "emoji-picker",             title: "Emoji Picker",               description: "Browse, search and copy any emoji instantly",     tag: TAGS.FUN,         type: CATEGORIES.STATIC, icon: "😀", color: "#f59e0b" },
  { id: 55, slug: "icon-finder",              title: "Icon Finder",                description: "Search and copy Unicode icons and symbols",       tag: TAGS.TOOL,        type: CATEGORIES.STATIC, icon: "🔣", color: "#6366f1" },
  { id: 56, slug: "rgb-mixer",                title: "RGB Color Mixer",            description: "Mix RGB channels and see the resulting color",    tag: TAGS.CREATIVE,    type: CATEGORIES.STATIC, icon: "🎛️", color: "#dc2626" },
  { id: 57, slug: "budget-planner",           title: "Budget Planner",             description: "Plan monthly budget with income and expenses",    tag: TAGS.FINANCE,     type: CATEGORIES.STATIC, icon: "📊", color: "#065f46" },
  { id: 58, slug: "number-guesser",           title: "Number Guesser",             description: "Guess the random number game with hints",         tag: TAGS.GAME,        type: CATEGORIES.STATIC, icon: "🔮", color: "#4c1d95" },
  { id: 59, slug: "dice-roller",              title: "Dice Roller",                description: "Roll any number of dice in any configuration",    tag: TAGS.FUN,         type: CATEGORIES.STATIC, icon: "🎲", color: "#991b1b" },
  { id: 60, slug: "tarot-card",               title: "Daily Tarot Card",           description: "Draw a daily tarot card for inspiration",         tag: TAGS.FUN,         type: CATEGORIES.STATIC, icon: "🔯", color: "#2e1065" },
  { id: 61, slug: "gratitude-journal",        title: "Gratitude Journal",          description: "Daily gratitude entries saved in your browser",   tag: TAGS.LIFESTYLE,   type: CATEGORIES.STATIC, icon: "🙏", color: "#7c2d12" },
  { id: 62, slug: "motivation-board",         title: "Vision Board",               description: "Create your personal digital vision board",       tag: TAGS.LIFESTYLE,   type: CATEGORIES.STATIC, icon: "✨", color: "#831843" },
  { id: 63, slug: "expense-tracker",          title: "Expense Tracker",            description: "Log and visualize daily expenses",                tag: TAGS.FINANCE,     type: CATEGORIES.STATIC, icon: "💸", color: "#7f1d1d" },
  { id: 64, slug: "keyboard-shortcut-ref",    title: "Keyboard Shortcuts Ref",     description: "Quick reference for popular app shortcuts",       tag: TAGS.INFO,        type: CATEGORIES.STATIC, icon: "⌨️", color: "#1e293b" },
  { id: 65, slug: "css-animation-playground", title: "CSS Animation Playground",   description: "Experiment with CSS animations visually",         tag: TAGS.CREATIVE,    type: CATEGORIES.STATIC, icon: "🎬", color: "#4f46e5" },

  // ─── DYNAMIC SITES (66–100) ────────────────────────────────────────────
  { id: 66, slug: "weather-app",              title: "Weather App",                description: "Live weather with 7-day forecast by location",    tag: TAGS.INFO,        type: CATEGORIES.DYNAMIC, icon: "🌤️", color: "#0369a1" },
  { id: 67, slug: "news-aggregator",          title: "News Aggregator",            description: "Latest headlines across categories in real time",  tag: TAGS.INFO,        type: CATEGORIES.DYNAMIC, icon: "📰", color: "#1e3a5f" },
  { id: 68, slug: "github-profile-viewer",    title: "GitHub Profile Viewer",      description: "View any GitHub profile with stats and repos",    tag: TAGS.TECH,        type: CATEGORIES.DYNAMIC, icon: "🐙", color: "#0f172a" },
  { id: 69, slug: "crypto-tracker",           title: "Crypto Price Tracker",       description: "Live cryptocurrency prices and market data",      tag: TAGS.FINANCE,     type: CATEGORIES.DYNAMIC, icon: "₿",  color: "#f59e0b" },
  { id: 70, slug: "movie-search",             title: "Movie Search",               description: "Search movies, view ratings and trailers",        tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "🎬", color: "#1c1917" },
  { id: 71, slug: "recipe-finder",            title: "Recipe Finder",              description: "Search thousands of recipes by ingredient",       tag: TAGS.LIFESTYLE,   type: CATEGORIES.DYNAMIC, icon: "🍳", color: "#92400e" },
  { id: 72, slug: "country-explorer",         title: "Country Explorer",           description: "Explore facts and flags of every country",        tag: TAGS.INFO,        type: CATEGORIES.DYNAMIC, icon: "🌍", color: "#065f46" },
  { id: 73, slug: "dictionary-app",           title: "Dictionary App",             description: "Look up word definitions, pronunciations",        tag: TAGS.EDUCATION,   type: CATEGORIES.DYNAMIC, icon: "📚", color: "#1e40af" },
  { id: 74, slug: "joke-generator",           title: "Joke Generator",             description: "Random jokes fetched from a public API",          tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "😂", color: "#d97706" },
  { id: 75, slug: "dog-breed-explorer",       title: "Dog Breed Explorer",         description: "Browse dog breeds with images and facts",         tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "🐕", color: "#92400e" },
  { id: 76, slug: "nasa-apod",                title: "NASA Photo of the Day",      description: "Daily astronomy picture from NASA's APOD API",    tag: TAGS.INFO,        type: CATEGORIES.DYNAMIC, icon: "🚀", color: "#0c0a09" },
  { id: 77, slug: "open-library-search",      title: "Book Search",                description: "Search millions of books via Open Library",       tag: TAGS.EDUCATION,   type: CATEGORIES.DYNAMIC, icon: "📖", color: "#7c2d12" },
  { id: 78, slug: "pokemon-explorer",         title: "Pokémon Explorer",           description: "Browse Pokémon with stats via PokéAPI",           tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "⚡", color: "#fbbf24" },
  { id: 79, slug: "ip-lookup",                title: "IP Address Lookup",          description: "Look up geolocation info for any IP address",     tag: TAGS.TECH,        type: CATEGORIES.DYNAMIC, icon: "🌐", color: "#0369a1" },
  { id: 80, slug: "meme-generator",           title: "Meme Generator",             description: "Create memes with top trending meme templates",   tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "😎", color: "#0f172a" },
  { id: 81, slug: "trivia-game",              title: "Live Trivia Game",           description: "Play trivia fetched from Open Trivia DB API",     tag: TAGS.GAME,        type: CATEGORIES.DYNAMIC, icon: "🏆", color: "#1d4ed8" },
  { id: 82, slug: "stock-ticker",             title: "Stock Ticker",               description: "Track stock prices with live chart previews",     tag: TAGS.FINANCE,     type: CATEGORIES.DYNAMIC, icon: "📈", color: "#064e3b" },
  { id: 83, slug: "art-gallery",              title: "Art Gallery",                description: "Browse artwork from the Metropolitan Museum",     tag: TAGS.CREATIVE,    type: CATEGORIES.DYNAMIC, icon: "🖼️", color: "#1e1b4b" },
  { id: 84, slug: "space-missions",           title: "Space Missions Tracker",     description: "Track past and upcoming space missions",          tag: TAGS.INFO,        type: CATEGORIES.DYNAMIC, icon: "🛸", color: "#0c0a09" },
  { id: 85, slug: "language-translator",      title: "Language Translator",        description: "Translate text between dozens of languages",      tag: TAGS.TOOL,        type: CATEGORIES.DYNAMIC, icon: "🌐", color: "#0f766e" },
  { id: 86, slug: "music-explorer",           title: "Music Explorer",             description: "Discover artists and tracks via iTunes API",      tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "🎵", color: "#be123c" },
  { id: 87, slug: "cocktail-finder",          title: "Cocktail Finder",            description: "Find cocktail recipes by ingredient or name",     tag: TAGS.LIFESTYLE,   type: CATEGORIES.DYNAMIC, icon: "🍹", color: "#9f1239" },
  { id: 88, slug: "exercise-library",         title: "Exercise Library",           description: "Browse workouts and exercises by muscle group",   tag: TAGS.HEALTH,      type: CATEGORIES.DYNAMIC, icon: "🏋️", color: "#14532d" },
  { id: 89, slug: "anime-search",             title: "Anime Search",               description: "Search anime titles with ratings via Jikan API",  tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "⛩️", color: "#4c1d95" },
  { id: 90, slug: "github-trending",          title: "GitHub Trending",            description: "Discover trending repositories on GitHub",        tag: TAGS.TECH,        type: CATEGORIES.DYNAMIC, icon: "🔥", color: "#7f1d1d" },
  { id: 91, slug: "color-name-finder",        title: "Color Name Finder",          description: "Find the name of any color from its hex code",    tag: TAGS.TOOL,        type: CATEGORIES.DYNAMIC, icon: "🎨", color: "#6d28d9" },
  { id: 92, slug: "advice-generator",         title: "Advice Generator",           description: "Get random life advice from the Advice Slip API", tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "💡", color: "#d97706" },
  { id: 93, slug: "cat-facts",                title: "Cat Facts",                  description: "Random cat facts from the Cat Facts API",         tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "🐱", color: "#0891b2" },
  { id: 94, slug: "us-holidays",              title: "US Holidays Calendar",       description: "View all US public holidays by year",             tag: TAGS.INFO,        type: CATEGORIES.DYNAMIC, icon: "📅", color: "#b45309" },
  { id: 95, slug: "zip-code-lookup",          title: "ZIP Code Lookup",            description: "Look up city and state for any US ZIP code",      tag: TAGS.UTILITY,     type: CATEGORIES.DYNAMIC, icon: "📮", color: "#0f172a" },
  { id: 96, slug: "iss-tracker",              title: "ISS Live Tracker",           description: "Track the International Space Station live",      tag: TAGS.INFO,        type: CATEGORIES.DYNAMIC, icon: "🛰️", color: "#172554" },
  { id: 97, slug: "age-in-seconds",           title: "Age in Seconds",             description: "See your exact age in seconds, updating live",    tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "⏱️", color: "#7f1d1d" },
  { id: 98, slug: "motivational-speech",      title: "Motivational Speech Gen",    description: "AI-style motivational speeches on any topic",     tag: TAGS.FUN,         type: CATEGORIES.DYNAMIC, icon: "🎤", color: "#1e1b4b" },
  { id: 99, slug: "covid-stats",              title: "COVID Stats Dashboard",      description: "Historical COVID-19 statistics by country",       tag: TAGS.INFO,        type: CATEGORIES.DYNAMIC, icon: "🦠", color: "#1e293b" },
  { id: 100,slug: "wikipedia-search",         title: "Wikipedia Search",           description: "Search and preview Wikipedia articles instantly", tag: TAGS.EDUCATION,   type: CATEGORIES.DYNAMIC, icon: "📖", color: "#1c1917" },
];

export function getSiteBySlug(slug) {
  return sites.find((s) => s.slug === slug) || null;
}

export function getStaticSites() {
  return sites.filter((s) => s.type === CATEGORIES.STATIC);
}

export function getDynamicSites() {
  return sites.filter((s) => s.type === CATEGORIES.DYNAMIC);
}
